# **Assignment 1 : Working with NumPy**

NumPy is a Python library used for:
*   arrays
*   mathematical operations
*   data science
*   machine learning


Normal Python lists are slower for calculations.
NumPy arrays are:
  *  faster
  *  optimized
  *  easier for mathematical work

In [ ]:
import numpy as np

1. Create a 1D NumPy array with integers from 1 to 20.

In [ ]:
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


a one-dimensional NumPy array containing integers from 1 to 20 is created using the np.arange() function. NumPy arrays are faster and more efficient for numerical operations compared to normal Python lists.

Perform the following operations:

a. Calculate the sum, mean, median, and standard deviation of the elements in the array.

In [ ]:
print(np.sum(arr))
#OR
arr.sum()

210


np.int64(210)

In [ ]:
print(np.mean(arr))
#OR
arr.mean()

10.5


np.float64(10.5)

In [ ]:
print(np.median(arr))

10.5


In [ ]:
print(np.std(arr))
#OR
arr.std()

5.766281297335398


np.float64(5.766281297335398)

numpy has builtin mathemetical functions which can be used to perform various mathematical operations as shown.

b. Find the indices of elements greater than 10 in the array.

In [ ]:
i = np.where(arr>10)
print(i)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


np.where(condition) helps in finding elements of array with specific conditions

**2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.**

a. Print the array.


In [ ]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


To create any Dimensional array we can use np.arange(start,end).reshape(shape) to create and nD type of array.

where reshape helps in shaping the array

b. Find the transpose of the array.

In [ ]:
np.transpose(arr)
#OR
arr.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

For transpose of a matrix or array we can use name.T or np.transpose(name)

c. Calculate the row-wise and column-wise sums of the array.

In [ ]:
print("Row wise sum:" ,np.sum(arr,axis=1))
print("Column wise sum:" , np.sum(arr,axis=0))

Row wise sum: [10 26 42 58]
Column wise sum: [28 32 36 40]


we use axis parameter to determine the operation , axis=1 decides ROW wise operations , axis=90 decides COLUMN wise operations

**3. Create two 3 X 3 arrays filled with random integers between 1 and 20.**

In [ ]:
arr1=np.random.randint(1,21,(3,3))
arr1

array([[ 3, 12,  8],
       [ 4, 18, 10],
       [17,  8, 10]])

In [ ]:
arr2=np.random.randint(1,21,(3,3))
arr2

array([[13,  1, 10],
       [11, 17,  5],
       [ 7, 11, 19]])

to create array with random integers we use np.random for random array and specifically for integers we use np.random.randint(start,end,shape)

a. Perform element-wise addition, subtraction, and multiplication.

In [ ]:
print("addition: \n", arr1+arr2)
print("substraction: \n", arr1-arr2)
print("multiplication: \n", arr1*arr2)

addition: 
 [[16 13 18]
 [15 35 15]
 [24 19 29]]
substraction: 
 [[-10  11  -2]
 [ -7   1   5]
 [ 10  -3  -9]]
multiplication: 
 [[ 39  12  80]
 [ 44 306  50]
 [119  88 190]]


We can Perform element-wise addition, subtraction, and multiplication using simple operations bettweeen array1 and array2 as shown

b. Compute the dot product of the two arrays.

In [ ]:
print("Dot Product: \n", np.dot(arr1,arr2))

Dot Product: 
 [[227 295 242]
 [320 420 320]
 [379 263 400]]


dot product between two arrays can be done using np.dot buildin function as shown.